---
- name: GPU Validation VM setup
  hosts: control_node
  gather_facts: false
  tasks:
    - name: VM Pre-tasks
      ansible.builtin.include_role:
        name: gpu-validation
        tasks_from: vm_pre.yaml

- name: GPU Validation
  hosts: target_nodes
  gather_facts: false
  roles:
    - gpu-validation

- name: GPU Validation VM cleanup
  hosts: control_node
  gather_facts: false
  tasks:
    - name: VM Post-tasks
      ansible.builtin.include_role:
        name: gpu-validation
        tasks_from: vm_post.yaml
