---
- name: RHEL AI Validation Playbook
  hosts: target_nodes
  gather_facts: false
  tasks:
    # Set-up the environment
    - name: Setup
      become: true
      ansible.builtin.import_tasks: tasks/setup.yaml
    - name: Check GPUs
      ansible.builtin.import_tasks: tasks/gpus.yaml
    - name: Check NVIDIA
      ansible.builtin.import_tasks: tasks/nvidia.yaml
    - name: Check iLab
      ansible.builtin.import_tasks: tasks/ilab.yaml
    - name: Cleanup
      become: true
      ansible.builtin.import_tasks: tasks/cleanup.yaml
