---
- name: Run lspci command and save output
  command: lspci -nn
  register: lspci_output

- name: Check each PCI device
  shell: |
    echo "{{ lspci_output.stdout }}" | grep '{{ item.key }}' | wc -l
  register: pci_count
  loop: "{{ pci_devices | dict2items }}"
  vars:
    expected_count: "{{ item.value }}"
  failed_when: pci_count.stdout | int != expected_count | int

- name: Set found_nvidia to true if NVIDIA is found
  set_fact:
    found_nvidia: true
  when: lspci_output.stdout is search("NVIDIA")
