---
- name: Construct the model_path
  ansible.builtin.set_fact:
    model_path: "{{ [model_path_base | regex_replace('/$', ''), model_name] | join('/') }}"

- name: Count the configured GPUs
  ansible.builtin.set_fact:
    num_gpus: '{{ pci_devices | dict2items | map(attribute="value") | sum }}'

- name: Run ilab config init
  ansible.builtin.expect:
    command: ilab config init
    responses:
      Enter the number of your choice: 0
      Do you want to restore these profiles to the default values: "y"
      Do you still want to continue: "y"
    timeout: 900
    echo: true

- name: Get rhelai config file content
  ansible.builtin.slurp:
    src: "{{ rhelai_config_file }}"
  register: rhelai_config_slurp

- name: Decode rhelai config yaml
  ansible.builtin.set_fact:
    rhelai_config: "{{ rhelai_config_slurp.content | b64decode | from_yaml }}"

- name: Update gpus lines in config
  ansible.builtin.set_fact:
    rhelai_config: "{{ rhelai_config | combine(update_dict, recursive=True) }}"
  vars:
    update_dict:
      evaluate:
        gpus: "{{ num_gpus }}"
      generate:
        teacher:
          vllm:
            gpus: "{{ num_gpus }}"
      serve:
        vllm:
          gpus: "{{ num_gpus }}"

# update_fact is preferred solution w/ ansible >= 2.15 (use updated.rhelai_config in the copy task below)
# - name: Find tensor-parallel-size argument in config
#   set_fact:
#     tps_index: "{{ rhelai_config.serve.vllm.vllm_args | ansible.utils.index_of('eq', '--tensor-parallel-size') + 1 }}"
# - name: Update tensor-parallel-size argument in config
#   ansible.utils.update_fact:
#     updates:
#       - path: "rhelai_config.serve.vllm.vllm_args[{{tps_index}}]"
#         value: "{{num_gpus}}"
#   register: updated

- name: Update rhelai config file
  ansible.builtin.copy:
    content: "{{ rhelai_config | to_nice_yaml(indent=2) }}"
    dest: "{{ rhelai_config_file }}"
    mode: "0644"

# Workaround for ansible < 2.15
- name: Adjust tensor-parallel-size (workaround for pre-2.15)
  ansible.builtin.shell: |
    rm -f /var/home/cloud-user/.config/instructlab/config.yaml.orig
    if ! perl -0777 -i.orig -pe "s/(vllm_args:[\\s\\n]*- --tensor-parallel-size[\\s\\n]*-) '\d+'/\1 '{{ num_gpus }}'/" \
      /var/home/cloud-user/.config/instructlab/config.yaml
    then
      exit 1
    fi
    if ! diff /var/home/cloud-user/.config/instructlab/config.yaml.orig /var/home/cloud-user/.config/instructlab/config.yaml
    then
      exit 2
    fi
  ignore_errors: true
  register: tps_replace_shell
  changed_when: tps_replace_shell.rc == 2
  failed_when: (tps_replace_shell.rc != 2 and tps_replace_shell.rc != 0)
