---
- name: Extract the repository host name
  ansible.builtin.set_fact:
    model_download_registry_host: "{{ model_download_repository_base | regex_replace('docker://(.*?)/.*', '\\1') }}"

- name: Log into registry if username is specified
  ansible.builtin.command:
    cmd: >
      podman login --username {{ model_download_registry_username | quote }} --password
      {{ model_download_registry_password | quote }} {{ model_download_registry_host | quote }}
  no_log: true
  when: model_download_registry_username
  changed_when: false

- name: Append --hf-token to model download args if specified
  ansible.builtin.set_fact:
    model_download_token_args: --hf-token {{ model_download_hf_token | quote }}
  no_log: true
  when: model_download_hf_token

- name: Append --release to model download args if specified
  ansible.builtin.set_fact:
    model_download_release_args: --release {{ model_download_release | quote }}
  when: model_download_release

- name: Construct the model repository url
  ansible.builtin.set_fact:
    model_download_repository: "{{ [model_download_repository_base | regex_replace('/$', ''), model_name] | join('/') | regex_replace('^/', '') }}"

- name: Download the inference model
  ansible.builtin.command:
    cmd: >
      ilab model download --repository {{ model_download_repository | quote }}
      {{ model_download_release_args | default('') }} {{ model_download_token_args | default('') }}
    creates: "{{ [model_path, 'config.json'] | join('/') }}"
  vars:
    ansible_command_timeout: 7200

- name: Create user systemd directory
  ansible.builtin.file:
    path: /var/home/cloud-user/.config/systemd/user
    state: directory
    mode: "0755"
    owner: cloud-user
    group: cloud-user

- name: Create ilab systemd service on RHEL AI machine
  ansible.builtin.template:
    src: templates/ilab-serve.service.j2
    dest: /var/home/cloud-user/.config/systemd/user/ilab-serve.service
    owner: cloud-user
    group: cloud-user
    mode: "0755"
  register: serviceconfig

- name: Stop the model serving service
  when: serviceconfig.changed  # noqa: no-handler - readability
  ansible.builtin.systemd_service:
    scope: user
    name: ilab-serve
    state: stopped

- name: Reload systemd config
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true

- name: Start the model serving service
  ansible.builtin.systemd_service:
    scope: user
    name: ilab-serve
    state: started

- name: Wait for vllm API to appear
  ansible.builtin.uri:
    url: http://localhost:8000/health
  register: api_result
  until: ("status" in api_result) and (api_result.status == 200)
  retries: 180  # 180 * 10 = 30 mins - this can be extremely slow in some environments https://github.com/containers/podman/issues/16541
  delay: 10
  changed_when: false

- name: Wait for vllm metrics endpoint to appear
  ansible.builtin.uri:
    url: http://localhost:8000/metrics/
  register: metrics_result
  until: ("status" in metrics_result) and (metrics_result.status == 200)
  retries: 12  # 12 * 10 = 2 mins after API appears
  delay: 10
  changed_when: false
