---
- name: Check for installed nvidia-driver RPM
  ansible.builtin.package_facts:
    manager: rpm

- name: Check if nvidia-driver installation is needed
  ansible.builtin.set_fact:
    _install_nvidia_driver: "{{ 'nvidia-driver' not in ansible_facts.packages }}"

- name: Install nvidia-driver RPM if needed
  when: _install_nvidia_driver
  block:
  - name: Blacklist nouveau kernel module
    become: true
    ansible.builtin.blockinfile:
      block: |
        blacklist nouveau
      path: /etc/modprobe.d/blacklist.conf
      create: true

  - name: Remove nouveau kernel module if loaded
    become: true
    ansible.builtin.command: modprobe -r nouveau
    ignore_errors: true

  - name: Add nvidia CUDA repo
    become: true
    yum_repository:
      name: nvidia-cuda-rhel9
      description: NVIDIA CUDA repo for RHEL 9
      baseurl: "{{nvidia_repo_url}}/$basearch/"
      gpgcheck: yes
      gpgkey: "{{nvidia_repo_url}}/$basearch/D42D0685.pub"

  - name: Add EPEL repository for DKMS support
    become: true
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/9/Everything/$basearch/
      enabled: 1
      gpgcheck: 1
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

  - name: Enable nvidia-driver RPM module
    become: true
    ansible.builtin.dnf:
      name: "@nvidia-driver:latest-dkms"
      state: present

  - name: Install the nvidia driver
    become: true
    ansible.builtin.dnf:
      name: cuda-drivers
      state: present

  - name: Refresh package facts after driver installation
    ansible.builtin.package_facts:
      manager: rpm

- name: Run nvidia-smi to list NVIDIA GPUs and count them
  ansible.builtin.shell: set -o pipefail && nvidia-smi --list-gpus | wc -l
  register: nvidia_gpu_count
  when: found_nvidia | default(false)
  changed_when: false

- name: Get some statistics about the NVIDIA GPU
  ansible.builtin.command: nvidia-smi --query-gpu=utilization.gpu,memory.used,memory.free,temperature.gpu --format=csv,nounits,noheader
  register: nvidia_smi_output
  when: found_nvidia | default(false)
  changed_when: false

- name: Display NVIDIA GPU statistics
  ansible.builtin.debug:
    msg: |
      GPU Utilization: {{ nvidia_smi_output.stdout.split(',')[0] }}%
      Memory Used: {{ nvidia_smi_output.stdout.split(',')[1].strip() }} MiB
      Memory Free: {{ nvidia_smi_output.stdout.split(',')[2].strip() }} MiB
      GPU Temperature: {{ nvidia_smi_output.stdout.split(',')[3].strip() }} C
  when:
    - found_nvidia | default(false)
    - not nvidia_smi_output.failed
