---
- name: Add DNS entry to /etc/resolv.conf if dns_server is set
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ dns_server }}"
    state: present
    insertafter: EOF
  when: dns_server != ""

- name: Install pciutils package
  ansible.builtin.dnf:
    use_backend: dnf4
    name: pciutils
    state: present

- name: Create /etc/ilab
  file:
    path: /etc/ilab
    state: directory

- name: Opt-out of Insights to use iLab
  file:
    path: /etc/ilab/insights-opt-out
    state: touch

- name: Copy scripts from local to RHEL AI machine
  copy:
    src: "{{ playbook_dir }}/scripts"
    dest: "/tmp"
    mode: '1777'
