---
- name: Check if image with the correct name already exists in Glance
  openstack.cloud.image_info:
    name: "{{ deploy_rhelai_image_name }}"
    ca_cert: "{{ deploy_rhelai_ca_cert_path }}"
  register: rhelai_image_info

- name: Set fact if image exists
  ansible.builtin.set_fact:
    rhelai_image_exists: "{{ (rhelai_image_info.images | length) > 0 }}"

- name: Download VM image
  ansible.builtin.get_url:
    url: "{{ deploy_rhelai_image_url }}"
    dest: "/tmp/{{ deploy_rhelai_image_url | basename }}"
    mode: '0644'
  when: not rhelai_image_exists

- name: Create glance image from RHELAI download source
  openstack.cloud.image:
    name: "{{deploy_rhelai_image_name}}"
    container_format: bare
    disk_format: qcow2
    filename: "/tmp/{{ deploy_rhelai_image_url | basename }}"
    visibility: public
    ca_cert: "{{ deploy_rhelai_ca_cert_path }}"
  when: not rhelai_image_exists

- name: Create flavor for RHELAI
  openstack.cloud.compute_flavor:
    name: "{{deploy_rhelai_flavor_name}}"
    ram: "{{deploy_rhelai_flavor_ram}}"
    vcpus: "{{deploy_rhelai_flavor_vcpus}}"
    disk: "{{deploy_rhelai_flavor_disk}}"
    extra_specs:
      "pci_passthrough:alias": "gpu-l4:{{deploy_rhelai_flavor_gpus}}"
      "hw:pci_numa_affinity_policy": "preferred"
      "hw:hide_hypervisor_id": "true"
    ca_cert: "{{ deploy_rhelai_ca_cert_path }}"
