---
- name: Extract the repository host name
  ansible.builtin.set_fact:
    gpu_validation_model_download_registry_host: "{{ gpu_validation_model_download_repository_base | regex_replace('docker://(.*?)/.*', '\\1') }}"

- name: Log into registry if username is specified
  ansible.builtin.command:
    cmd: >
      podman login --username {{ gpu_validation_model_download_registry_username | quote }} --password
      {{ gpu_validation_model_download_registry_password | quote }} {{ gpu_validation_model_download_registry_host | quote }}
  no_log: true
  when: gpu_validation_model_download_registry_username
  changed_when: false

- name: Append --hf-token to model download args if specified
  ansible.builtin.set_fact:
    gpu_validation_model_download_token_args: --hf-token {{ gpu_validation_model_download_hf_token | quote }}
  no_log: true
  when: gpu_validation_model_download_hf_token

- name: Create user systemd directory
  ansible.builtin.file:
    path: /home/cloud-user/.config/systemd/user
    state: directory
    mode: "0755"
    owner: cloud-user
    group: cloud-user

- name: Create vllm model serving systemd service
  ansible.builtin.template:
    src: templates/vllm-serve.service.j2
    dest: /home/cloud-user/.config/systemd/user/vllm-serve.service
    owner: cloud-user
    group: cloud-user
    mode: "0755"
  register: serviceconfig

- name: Stop the model serving service
  when: serviceconfig.changed  # noqa: no-handler - readability
  ansible.builtin.systemd_service:
    scope: user
    name: vllm-serve
    state: stopped

- name: Reload systemd config
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true

- name: Start the model serving service
  ansible.builtin.systemd_service:
    scope: user
    name: vllm-serve
    state: started

- name: Wait for vllm API to appear
  ansible.builtin.uri:
    url: http://localhost:8000/health
  register: api_result
  until: ("status" in api_result) and (api_result.status == 200)
  retries: 180  # 180 * 10 = 30 mins - this includes the time to download the model
  delay: 10
  changed_when: false

- name: Wait for vllm metrics endpoint to appear
  ansible.builtin.uri:
    url: http://localhost:8000/metrics/
  register: metrics_result
  until: ("status" in metrics_result) and (metrics_result.status == 200)
  retries: 12  # 12 * 10 = 2 mins after API appears
  delay: 10
  changed_when: false
