---
- name: Check for installed nvidia-driver RPM
  ansible.builtin.package_facts:
    manager: rpm

- name: Check if nvidia-driver installation is needed
  ansible.builtin.set_fact:
    _install_nvidia_driver: "{{ 'nvidia-driver' not in ansible_facts.packages }}"

- name: Install nvidia-driver RPM if needed
  when: _install_nvidia_driver
  block:
    - name: Blacklist nouveau kernel module
      ansible.builtin.blockinfile:
        block: |
          blacklist nouveau
        path: /etc/modprobe.d/blacklist.conf
        mode: "0644"
        create: true

    - name: Remove nouveau kernel module if loaded
      ansible.builtin.command: modprobe -r nouveau
      failed_when: false
      changed_when: false

    - name: Add nvidia CUDA repo
      ansible.builtin.yum_repository:
        name: nvidia-cuda-rhel9
        description: NVIDIA CUDA repo for RHEL 9
        baseurl: "{{ gpu_validation_nvidia_repo_url }}/$basearch/"
        gpgcheck: true
        gpgkey: "{{ gpu_validation_nvidia_repo_url }}/$basearch/D42D0685.pub"

    - name: Add EPEL repository for DKMS support
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/9/Everything/$basearch/
        enabled: 1
        gpgcheck: 1
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

    - name: Enable nvidia-driver RPM module
      ansible.builtin.dnf:
        name: "@nvidia-driver:latest-dkms"
        state: present

    - name: Install the nvidia CUDA driver
      ansible.builtin.dnf:
        name: cuda-drivers
        state: present

    - name: Refresh package facts after driver installation
      ansible.builtin.package_facts:
        manager: rpm
