---
- name: Overwrite DNS entries in /etc/resolv.conf if gpu_validation_dns_server is set
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver {{ gpu_validation_dns_server }}
    mode: '0644'
  when: gpu_validation_dns_server != ""

- name: Install pciutils package
  ansible.builtin.dnf:
    use_backend: dnf4
    name: pciutils
    state: present

- name: Install pip package
  ansible.builtin.dnf:
    use_backend: dnf4
    name: python-pip
    state: present

- name: Install podman package
  ansible.builtin.dnf:
    use_backend: dnf4
    name: podman
    state: present

- name: Copy scripts from local to RHEL AI machine
  ansible.builtin.copy:
    src: "{{ role_path }}/files/scripts"
    dest: /tmp
    mode: "1777"
