---
- name: RHEL AI VM setup
  when: gpu_validation_enabled | bool
  block:
    - name: VM Cleanup (Pre)
      ansible.builtin.import_tasks: vm_cleanup.yaml
      when: gpu_validation_pre_cleanup_enabled | bool

    - name: VM image import
      ansible.builtin.import_tasks: vm_image.yaml

    - name: Set up SSH key for VM
      ansible.builtin.import_tasks: vm_sshkey.yaml

    - name: Set up networking
      ansible.builtin.import_tasks: vm_net.yaml

    - name: VM Deploy
      ansible.builtin.import_tasks: vm_deploy.yaml
